name: JSON Validator
on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate textures.json
        run: |
          for file in $(find fonts -name 'textures.json'); do
            ajv validate -s .github/schema/textures.json -d $file || exit 1
          done

      - name: Validate fonts.json
        run: ajv validate -s .github/schema/fonts.json -d fonts.json

      - name: Validate tileables.json
        run: ajv validate -s .github/schema/tileables.json -d tileables.json